spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auctiondb}
    username: ${SPRING_DATASOURCE_USERNAME:auction}
    password: ${SPRING_DATASOURCE_PASSWORD:auction}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
