spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/subastasdb}
    username: ${SPRING_DATASOURCE_USERNAME:subastas}
    password: ${SPRING_DATASOURCE_PASSWORD:subastas}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
